# Generated by Django 2.2 on 2021-05-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=70, verbose_name='Email')),
                ('phone', models.CharField(max_length=12, verbose_name='Contact No.')),
                ('subject', models.CharField(max_length=80, verbose_name='Message Title')),
                ('message', models.TextField(max_length=300, verbose_name='Message')),
            ],
        ),
    ]
