# Generated by Django 2.2 on 2021-05-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_auto_20210523_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(max_length=350, null=True, verbose_name='Note'),
        ),
    ]
